//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordsContext : DbContext
    {
        public WordsContext()
            : base("name=WordsContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<WordRus> WordRus { get; set; }
        public virtual DbSet<WordTranslation> WordTranslation { get; set; }
        public virtual DbSet<WordRelated> WordRelated { get; set; }
        public virtual DbSet<WordRusToRelated> WordRusToRelated { get; set; }
    }
}
